### ISSUE TITLE
Support directory recursing instead of relying on all the files to be passed on the command line

### ISSUE THREAD

**Issue by scheibo** [tusharsadhwani/zigimports#5] opened 2024-09-03 18:36 UTC
Being able to do `zigimport .` (like `zig fmt`) is a much better UX, especially for large projects (also, passing all the files as args doen't scale as you will eventually hit `ARG_MAX`)

**Comment by tusharsadhwani** [comment] 2024-09-03 18:39
Does `.` imply `./**/*.zig`, i.e. zig files in arbitrarily deep folders?

**Comment by tusharsadhwani** [comment] 2024-09-03 19:46
This has been implemented in https://github.com/tusharsadhwani/zigimports/commit/2cf7d52acda465d3fc42a04af9eb69b94106d7b6

**Comment by tusharsadhwani** [comment] 2024-09-03 19:50
The way I'm recursing right now, all files and directories starting with `.` are ignored.

Can you provide the repository that you're testing on? The couple that I'm using to test don't reproduce the memory leak.

**Comment by tusharsadhwani** [comment] 2024-09-03 20:22
Alright, the leak is happening due to a bug caused by symlinks to paths that don't exist. Fixing...

**Comment by tusharsadhwani** [comment] 2024-09-03 20:32
Fixed with https://github.com/tusharsadhwani/zigimports/commit/b3e9bb2a25b03bfbfd767eb7d0cdce1b334fda0c, can you check?

**Comment by tusharsadhwani** [comment] 2024-09-03 20:33
In hindsight I should have been less confident and made a PR.

**Comment by tusharsadhwani** [comment] 2024-09-05 20:40
```console
$ ls -lah ./examples/zig/legacy/lib
total 0
drwxr-xr-x@ 3 tusharsadhwani  staff    96B Sep  6 02:05 .
drwxr-xr-x@ 5 tusharsadhwani  staff   160B Sep  6 02:05 ..
lrwxr-xr-x@ 1 tusharsadhwani  staff    11B Sep  6 02:05 pkmn -> ../../../..
```

Infinite recursion. Of course. Disabling symlink following...

**Comment by tusharsadhwani** [comment] 2024-09-05 21:52
Symlinks have been handled, linting the `pkmn/engine` project works on my machine. Can you confirm?

P.S. Thanks for this project, I found a bunch of edge cases.

**Comment by tusharsadhwani** [comment] 2024-09-06 09:43
```console
$ git checkout 6be9a77596ce8b2474b90f5269880992aa292fa2
[...]

$ zigimports .
./src/tools/transitions.zig:6:0: swtch is unused
./src/lib/gen2/mechanics.zig:37:0: PointerType is unused
[ ... 40 lines hidden ... ]
./src/lib/gen1/test.zig:6:0: DEBUG is unused

$ git checkout 745843a652c717c2d7f74570d10e44574cde4c53
Previous HEAD position was 6be9a775 change sleep mask onstant name after ziglang/zig#21231
HEAD is now at 745843a6 rm unused imports

$ zigimports .
./src/tools/transitions.zig:6:0: swtch is unused
./src/lib/gen2/mechanics.zig:6:0: DEBUG is unused
[ ... 23 lines hidden ... ]
./src/lib/gen1/test.zig:6:0: DEBUG is unused
```

https://github.com/tusharsadhwani/zigimports/commit/10dfc7c6b982c33b9968939e7888f58a6bb247ce seems to work for me. Can you check once again and confirm it's broken?

**Comment by tusharsadhwani** [comment] 2024-09-06 09:50
Running `zigimports` without any arguments will throw an error now, fixed in https://github.com/tusharsadhwani/zigimports/commit/3a1bf3ea98ab25cbd1444e15d5dc024e3f679f83

**Comment by tusharsadhwani** [comment] 2024-09-06 15:17
I am running this locally on an M1 mac and it works. This is very weird

I'll add debug logging and a `--debug` flag, we'll figure it out then

**Comment by tusharsadhwani** [comment] 2024-09-07 00:40
Added debug logging, can you run `zigimports . --debug` and send the output?

And run `git rev-parse HEAD` and `git status` and send the output as well, just in case.

**Comment by tusharsadhwani** [comment] 2024-09-07 00:41
Actually wait. Let me add debug logs to the recursive find files part too.

**Comment by tusharsadhwani** [comment] 2024-09-07 00:46
Okay, done.

**Comment by tusharsadhwani** [comment] 2024-09-08 03:41
Yeah, a message should be printed in case of errors. Thanks for the help!

**Comment by tusharsadhwani** [comment] 2024-09-08 11:41
Very weird that I'm unable to reproduce this at all. I re-created node modules and ran zigimports, in your output it seems like it starts failing after ~1400 files opened, but in my case it opened all 19000+ files with no errors.

```console
$ uname -a                       
Darwin Tushars-MacBook-Air.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:52 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T8103 arm64
```

[output.txt](https://github.com/user-attachments/files/16921997/output.txt)

No `ProcessFdQuotaExceeded` for me, runs just fine. So the point at which `ProcessFdQuotaExceeded` happens is a bit unpredictable. I'll look into not having this happening entirely.

**Comment by tusharsadhwani** [comment] 2024-09-08 12:06
Found the culprit, `_get_zig_files` was opening files recursively, but was doing `defer file.close()` so directories stay open until the entire directory contents have been recursed into.

Should be fixed now.

**Comment by tusharsadhwani** [comment] 2024-09-08 12:08
Also the reason why it doesn't reproduce for me is probably because of `ulimit`:

```console
$ ulimit -n
8192
```

Regarding skipping `node_modules`, even with node_modules present, `zigimports .` seems to finish in 1 second for me, so I think it's fine to not do for now.

**Closed as completed** 2024-09-08 20:28 UTC
